
###

GET  https://localhost:7095/api/admin/echo/sadasd/asdasd?a=111&b=2 HTTP/1.1


###

POST  https://localhost:7095/api/admin/echo?a=111&b=2 HTTP/1.1
content-type: application/x-www-form-urlencoded

sql=set+statistics+io+on%0Aset+statistics+time+on%0Aset+statistics+profile+on%0Aselect+'%22111%22'+as+F%2C+*%0Afrom%0Asys.objects%0A%0Aselect+'%22222%22'+as+F%2C+*%0Afrom%0Asys.objects&rowcount=100


###

POST  https://localhost:7095/api/admin/echo?a=111&b=2 HTTP/1.1
content-type: application/json

{a:[1,"111"]}