###
GET  https://localhost:7095/api/admin/echo/jsonnode/asdasd?a=111&b=2&a=a222 HTTP/1.1

###
GET  https://localhost:7095/api/admin/echo/jsonnode/async/asdasd?a=111&b=2&a=a222 HTTP/1.1


###
GET  https://localhost:7095/api/admin/strongtype?a=111&b=2&a=a222 HTTP/1.1

###
POST  https://localhost:7095/api/admin/strongtype/jtokenparse?a=111&b=2&a=a222 HTTP/1.1

{
    /* aaa */
    "a" : [ "1111" ]
    , "b" : "2222"
    , "c" : 333
     , "d" : {"a": 1}
    , "e" : { "c": 1112 }
    , "g" :  [ {"a": 1 }, {"b": 2, "c": 3}]
   
}

###
POST  https://localhost:7095/api/admin/strongtype/jsonnodeparse?a=111&b=2&a=a222 HTTP/1.1

{
    "a" : [ "1111" ],
    "b" : "2222", /* asd */
    "c" : 333,
    "d" : {"a": 1},
    "f" : [ {"a": 1 }, {"b": 2, "c": 3}],

}


###
# ok
POST  https://localhost:7095/api/admin/echo/jsonnode/a/bbbbb?a=111&b=2 HTTP/1.1
content-type: application/x-www-form-urlencoded

sql=set+statistics+io+on%0Aset+statistics+time+on%0Aset+statistics+profile+on%0Aselect+'%22111%22'+as+F%2C+*%0Afrom%0Asys.objects%0A%0Aselect+'%22222%22'+as+F%2C+*%0Afrom%0Asys.objects&rowcount=100


###
# ok
POST  https://localhost:7095/api/admin/echo/jsonnode/async/bbbbb?a=111&b=2 HTTP/1.1
content-type: application/x-www-form-urlencoded

sql=set+statistics+io+on%0Aset+statistics+time+on%0Aset+statistics+profile+on%0Aselect+'%22111%22'+as+F%2C+*%0Afrom%0Asys.objects%0A%0Aselect+'%22222%22'+as+F%2C+*%0Afrom%0Asys.objects&rowcount=100


###
# ok
POST  https://localhost:7095/api/admin/echo/jsonnode/async/bbbbb HTTP/1.1
content-type: application/json

{ "a": 



1 }

###
# failed because without request content body
POST  https://localhost:7095/api/admin/echo/jsonnode/a/bbbbb?a=111&b=2 HTTP/1.1
content-type: application/json

[]


###
#已修复四选一有Bug
# AmbiguousMatchException
POST  https://localhost:7095/api/admin/echo/jsonnode HTTP/1.1
content-type: application/json

{"a":9999,"b":[1,2,3,5]}

###
#已修复四选一有Bug
# AmbiguousMatchException
# Async 大写 A 则 失败
POST  https://localhost:7095/api/admin/echo/jsonnode/async/aaa?a=10 HTTP/1.1
content-type: application/json

{"a":9999,"b":[1,2,3,5]}

###
PUT  https://localhost:7095/api/admin/echo/jsonnode?a=111&b=2 HTTP/1.1
content-type: application/json

{}

###
PUT  https://localhost:7095/api/admin/echo/jsonnode/async/aa/zz HTTP/1.1
content-type: application/json

{"a":1}

###

GET  https://localhost:7095/api/admin/echo/jsonnode/async/sadasd/asdasd?{a:19} HTTP/1.1

